### ISSUE TITLE
New user, no bank details set up give warning

### ISSUE THREAD

**Issue by ianleggett** [ianleggett/TinanceUI#10]
![issue0005](https://user-images.githubusercontent.com/827175/126843800-fe141876-0361-4325-bd93-3924feac5d9d.png)
Should be no warning message - investigate the issue & fix

**Comment by meditations** [comment]
You haven't setup your bank account, please add bank account.

**Comment by ianleggett** [comment]
The field labels still do not show. API now returns the data as required
![image](https://user-images.githubusercontent.com/827175/127128251-2fd0abd8-4891-497f-a89a-26e5d5ac9cc0.png)

**Comment by laozhu** [comment]
Fixed @ianleggett, please review.

**Comment by meditations** [comment]
<img width="1210" alt="Screen Shot 2021-08-02 at 11 19 42 AM" src="https://user-images.githubusercontent.com/1285857/127792371-0e881346-b5e8-4984-965a-57f5bb2d6ced.png">

On demo.tinance.io, bank label still not showing. @ianleggett is the code on demo site the latest one? and the bank label api has updated accordingly?

**Comment by meditations** [comment]
Please display the bank details as:
1. Bank name
2. Bank address
3. Swift code (optional)
4. Account name
5. Account number
6. Note

**Comment by meditations** [comment]
It should be the cache problem of the Internet browser, question how the user will keep updated with our new updates.

**Comment by meditations** [comment]
<img width="918" alt="Screen Shot 2021-08-02 at 10 28 40 PM" src="https://user-images.githubusercontent.com/1285857/127861957-ccb08941-0c7b-40db-ab74-b8cc162b8f8c.png">

Most of the bank labels are show, except "Note" field.
